import React, { useEffect, useState, useCallback } from 'react';
import { useSelector } from 'react-redux';
import { apiFetch } from '../../utils/api';
import { Card } from '../../components/ui/Card';
import { Loader } from '../../components/ui/Loader';
import { ErrorState } from '../../components/ui/ErrorState';
import { EmptyState } from '../../components/ui/EmptyState';
import { Button } from '../../components/ui/Button';
import { Table } from '../../components/ui/Table';
import { SelectField } from '../../components/ui/SelectField';
import { RestaurantCell } from '../../components/ui/RestaurantCell';

const STATUS_STYLES = {
  PENDING: 'bg-amber-100 text-amber-800',
  APPROVED: 'bg-emerald-100 text-emerald-800',
  TRANSFER_CREATED: 'bg-sky-100 text-sky-800',
  DISPATCHED: 'bg-indigo-100 text-indigo-800',
  COMPLETED: 'bg-green-100 text-green-800',
  REJECTED: 'bg-rose-100 text-rose-800',
  FULFILLED: 'bg-teal-100 text-teal-800',
};

const TRANSFER_STATUS_STYLES = {
  PENDING: 'bg-amber-100 text-amber-800',
  APPROVED: 'bg-blue-100 text-blue-800',
  IN_TRANSIT: 'bg-indigo-100 text-indigo-800',
  COMPLETED: 'bg-emerald-100 text-emerald-800',
  REJECTED: 'bg-rose-100 text-rose-800',
};

const FILTER_OPTIONS = [
  { value: '', label: 'All Statuses' },
  { value: 'PENDING', label: 'Pending' },
  { value: 'APPROVED', label: 'Approved' },
  { value: 'TRANSFER_CREATED', label: 'Transfer Created' },
  { value: 'DISPATCHED', label: 'Dispatched' },
  { value: 'COMPLETED', label: 'Completed' },
  { value: 'REJECTED', label: 'Rejected' },
  { value: 'FULFILLED', label: 'Fulfilled' },
];

export function BranchStoreRequestsPage() {
  const [requests, setRequests] = useState([]);
  const [warehouses, setWarehouses] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [processingId, setProcessingId] = useState(null);
  const [statusFilter, setStatusFilter] = useState('');

  const warehouse = useSelector((state) => state.warehouse);

  const fetchData = useCallback(async () => {
    try {
      setLoading(true);
      const [reqRes, whRes] = await Promise.all([
        apiFetch('warehouse/store-requests'),
        apiFetch('warehouse'),
      ]);
      setRequests(Array.isArray(reqRes) ? reqRes : []);
      setWarehouses(Array.isArray(whRes) ? whRes : []);
      setError(null);
    } catch (err) {
      setError(err.message || 'Failed to load branch store requests.');
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  const handleApprove = async (id) => {
    setProcessingId(id);
    try {
      const warehouseId = warehouse?.warehouseId || (warehouses.length > 0 ? warehouses[0].id : null);
      await apiFetch(`warehouse/store-requests/${id}/approve`, {
        method: 'POST',
        body: JSON.stringify({
          warehouseId: warehouseId ? Number(warehouseId) : undefined,
        }),
      });
      fetchData();
    } catch (err) {
      alert(err.message || 'Approval failed.');
    } finally {
      setProcessingId(null);
    }
  };

  const handleReject = async (id) => {
    if (!confirm('Reject this store request?')) return;
    setProcessingId(id);
    try {
      await apiFetch(`warehouse/store-requests/${id}/reject`, { method: 'POST' });
      fetchData();
    } catch (err) {
      alert(err.message || 'Rejection failed.');
    } finally {
      setProcessingId(null);
    }
  };

  if (loading && requests.length === 0) return <Loader label="Loading branch store requests..." />;
  if (error) return <ErrorState error={error} retry={fetchData} />;

  const filteredRequests = statusFilter
    ? requests.filter((req) => req.status === statusFilter)
    : requests;

  const columns = [
    {
      header: 'Request #',
      key: 'requestNumber',
      render: (row) => (
        <span className="flex items-center gap-2">
          <span className="font-medium text-slate-900">{row.requestNumber}</span>
          {row.isAutoGenerated && (
            <span className="inline-flex items-center rounded-full px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide bg-violet-100 text-violet-800">
              Auto
            </span>
          )}
        </span>
      ),
    },
    {
      header: 'Restaurant',
      key: 'restaurant',
      render: (row) => <RestaurantCell name={row.restaurantName} id={row.restaurantId} />,
    },
    {
      header: 'Status',
      key: 'status',
      render: (row) => (
        <span className={`inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-semibold ${STATUS_STYLES[row.status] || 'bg-slate-100 text-slate-800'}`}>
          {row.status}
        </span>
      ),
    },
    { header: 'Requested By', key: 'requestedBy', render: (row) => row.requestedBy?.name || '—' },
    {
      header: 'Items',
      key: 'items',
      render: (row) => (
        <span className="inline-flex items-center rounded-full bg-slate-100 px-2.5 py-0.5 text-xs font-semibold text-slate-700">
          {row.items?.length || row.itemCount || 0} items
        </span>
      ),
    },
    { header: 'Request Date', key: 'createdAt', render: (row) => <span className="text-xs text-slate-500">{new Date(row.createdAt).toLocaleDateString()}</span> },
    { header: 'Approved Date', key: 'approvedAt', render: (row) => <span className="text-xs text-slate-500">{row.approvedAt ? new Date(row.approvedAt).toLocaleDateString() : '—'}</span> },
    { header: 'Completed Date', key: 'completedAt', render: (row) => <span className="text-xs text-slate-500">{row.completedAt ? new Date(row.completedAt).toLocaleDateString() : '—'}</span> },
    { header: 'Transfer #', key: 'transferNumber', render: (row) => row.transferNumber ? <span className="text-xs font-medium text-slate-700">{row.transferNumber}</span> : '—' },
    {
      header: 'Transfer Status',
      key: 'transferStatus',
      render: (row) => row.transferStatus ? (
        <span className={`inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-semibold ${TRANSFER_STATUS_STYLES[row.transferStatus] || 'bg-slate-100 text-slate-800'}`}>
          {row.transferStatus}
        </span>
      ) : '—',
    },
    {
      header: 'Actions',
      key: 'actions',
      render: (row) => {
        if (processingId === row.id) return <span className="text-xs text-slate-400">Processing...</span>;
        if (row.status === 'PENDING') {
          return (
            <div className="flex gap-2">
              <Button
                variant="primary"
                className="px-2.5 py-1 text-xs"
                onClick={() => handleApprove(row.id)}
              >
                Approve
              </Button>
              <Button
                variant="secondary"
                className="px-2.5 py-1 text-xs"
                onClick={() => handleReject(row.id)}
              >
                Reject
              </Button>
            </div>
          );
        }
        return null;
      },
    },
  ];

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-slate-900">Branch Store Requests</h1>
        <p className="text-sm text-slate-500">Complete history of inventory requests from restaurant stores</p>
      </div>

      <Card title="Store Requests" eyebrow="From Restaurants">
        <div className="mb-4 max-w-xs">
          <SelectField
            label="Status"
            options={FILTER_OPTIONS}
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value)}
          />
        </div>
        {filteredRequests.length === 0 ? (
          <EmptyState message={statusFilter ? `No ${statusFilter.replace(/_/g, ' ').toLowerCase()} store requests.` : 'No store requests yet.'} />
        ) : (
          <Table columns={columns} data={filteredRequests} emptyMessage="No store requests found." />
        )}
      </Card>
    </div>
  );
}
