export const DEFAULT_PAGINATION_LIMIT = 20;
export const DEFAULT_PAGINATION_OFFSET = 0;
export const DEFAULT_PAGINATION_MAX_LIMIT = 50;

export const TABLES_PAGINATION_MAX_LIMIT = 100;
export const TABLES_PAGINATION_DEFAULT_LIMIT = DEFAULT_PAGINATION_LIMIT;
