-- AlterTable
ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "accepted_at" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "prepared_at" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "delivered_at" TIMESTAMP(3);

-- AlterTable
ALTER TABLE "menu_items" ADD COLUMN IF NOT EXISTS "discount_price" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "image_url" TEXT,
ADD COLUMN IF NOT EXISTS "food_type" TEXT NOT NULL DEFAULT 'VEG',
ADD COLUMN IF NOT EXISTS "spicy_level" INTEGER,
ADD COLUMN IF NOT EXISTS "ingredients" TEXT,
ADD COLUMN IF NOT EXISTS "is_best_selling" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "popularity_score" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "rating" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "customizable_options" JSONB;
