import React, { useEffect, useState } from 'react';
import { apiFetch } from '../utils/api';
import { Card } from '../components/ui/Card';
import { Loader } from '../components/ui/Loader';
import { ErrorState } from '../components/ui/ErrorState';
import { Button } from '../components/ui/Button';
import { Table } from '../components/ui/Table';
import { Modal } from '../components/ui/Modal';
import { TextField } from '../components/ui/TextField';
import { SelectField } from '../components/ui/SelectField';
import { useSelector } from 'react-redux';

export function RequisitionsPage() {
  const [requisitions, setRequisitions] = useState([]);
  const [ingredients, setIngredients] = useState([]);
  const [warehouses, setWarehouses] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  const restaurantId = useSelector((state) => state.restaurant.restaurantId);
  const currentUser = useSelector((state) => state.auth.user);
  const userRole = currentUser?.role || 'STORE_MANAGER';

  const [modalOpen, setModalOpen] = useState(false);
  const [notes, setNotes] = useState('');
  const [reqItems, setReqItems] = useState([{ ingredientId: '', quantity: 1 }]);
  const [submitError, setSubmitError] = useState('');

  const fetchData = async () => {
    try {
      setLoading(true);
      const [reqRes, ingRes, whRes] = await Promise.all([
        apiFetch(`stock-movement/requisitions?restaurantId=${restaurantId}`),
        apiFetch('master/ingredients'),
        apiFetch('warehouse'),
      ]);
      setRequisitions(reqRes);
      setIngredients(ingRes);
      setWarehouses(whRes);
      if (ingRes.length > 0) {
        setReqItems([{ ingredientId: ingRes[0].id, quantity: 1 }]);
      }
      setError(null);
    } catch (err) {
      setError(err.message || 'Failed to load requisitions.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchData();
  }, [restaurantId]);

  const handleItemChange = (idx, field, val) => {
    const updated = [...reqItems];
    updated[idx][field] = val;
    setReqItems(updated);
  };

  const addItemRow = () => {
    const defaultIngId = ingredients[0]?.id || '';
    setReqItems([...reqItems, { ingredientId: defaultIngId, quantity: 1 }]);
  };

  const removeItemRow = (idx) => {
    if (reqItems.length === 1) return;
    setReqItems(reqItems.filter((_, i) => i !== idx));
  };

  const handleCreateRequisition = async (e) => {
    e.preventDefault();
    setSubmitError('');
    try {
      await apiFetch('stock-movement/requisitions', {
        method: 'POST',
        body: JSON.stringify({
          restaurantId: Number(restaurantId),
          notes: notes || null,
          items: reqItems.map((item) => ({
            ingredientId: Number(item.ingredientId),
            quantity: Number(item.quantity),
          })),
        }),
      });
      setModalOpen(false);
      setNotes('');
      fetchData();
    } catch (err) {
      setSubmitError(err.message || 'Failed to create requisition.');
    }
  };

  const handleFulfill = async (reqId) => {
    if (warehouses.length === 0) {
      alert('No warehouses available to fulfill from.');
      return;
    }
    try {
      await apiFetch(`stock-movement/requisitions/${reqId}/fulfill`, {
        method: 'PUT',
        body: JSON.stringify({ warehouseId: warehouses[0].id }),
      });
      fetchData();
    } catch (err) {
      alert(err.message || 'Fulfillment failed.');
    }
  };

  if (loading && requisitions.length === 0) return <Loader label="Loading store requisitions..." />;
  if (error) return <ErrorState error={error} />;

  const canFulfill = ['SUPER_ADMIN', 'INVENTORY_MANAGER', 'WAREHOUSE_MANAGER'].includes(userRole);

  const columns = [
    { header: 'Requisition #', key: 'requisitionNumber' },
    { header: 'Status', key: 'status', render: (row) => {
      const colors = {
        PENDING: 'bg-amber-100 text-amber-800',
        APPROVED: 'bg-blue-100 text-blue-800',
        FULFILLED: 'bg-emerald-100 text-emerald-800',
        REJECTED: 'bg-rose-100 text-rose-800',
      };
      return (
        <span className={`px-2 py-1 text-xs font-semibold rounded-full ${colors[row.status]}`}>
          {row.status}
        </span>
      );
    }},
    { header: 'Auto-Generated', key: 'isAutoGenerated', render: (row) => row.isAutoGenerated ? (
      <span className="px-2 py-1 text-xs font-semibold rounded-full bg-blue-100 text-blue-800">Auto</span>
    ) : 'Manual' },
    { header: 'Requested By', key: 'requestedBy', render: (row) => row.requestedBy?.name },
    { header: 'Notes', key: 'notes', render: (row) => row.notes || '—' },
    { header: 'Created', key: 'createdAt', render: (row) => new Date(row.createdAt).toLocaleDateString() },
    { header: 'Actions', key: 'actions', render: (row) => (
      row.status === 'PENDING' && canFulfill ? (
        <Button variant="secondary" className="py-1 px-2.5 text-xs" onClick={() => handleFulfill(row.id)}>
          Fulfill
        </Button>
      ) : null
    )},
  ];

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-slate-900">Restaurant Requisitions</h1>
          <p className="text-sm text-slate-500">Store room replenishment requests from the central warehouse.</p>
        </div>
        <Button onClick={() => setModalOpen(true)}>New Requisition</Button>
      </div>

      <Card title="Requisition History" eyebrow="Warehouse to Store">
        <Table columns={columns} data={requisitions} emptyMessage="No requisitions found." />
      </Card>

      <Modal open={modalOpen} title="Create Store Requisition" onClose={() => setModalOpen(false)} maxWidth="max-w-3xl">
        <form onSubmit={handleCreateRequisition} className="space-y-6">
          <TextField label="Notes" value={notes} onChange={(e) => setNotes(e.target.value)} placeholder="e.g. Weekly store replenishment" />

          <div className="space-y-3">
            <div className="flex justify-between items-center">
              <h4 className="text-sm font-semibold text-slate-900">Items Required</h4>
              <Button variant="secondary" className="py-1 px-3 text-xs" onClick={addItemRow}>+ Add Item</Button>
            </div>
            {reqItems.map((item, idx) => (
              <div key={idx} className="grid grid-cols-[2fr_1fr_auto] gap-3 items-end bg-slate-50 p-3 rounded-xl border border-slate-100">
                <SelectField
                  label="Ingredient"
                  value={item.ingredientId}
                  onChange={(e) => handleItemChange(idx, 'ingredientId', e.target.value)}
                  options={ingredients.map((ing) => ({ label: `${ing.name} (${ing.sku})`, value: ing.id }))}
                  required
                />
                <TextField
                  label="Quantity"
                  type="number"
                  step="any"
                  value={item.quantity}
                  onChange={(e) => handleItemChange(idx, 'quantity', e.target.value)}
                  required
                />
                <Button variant="danger" className="py-2.5 px-3 mb-0.5" onClick={() => removeItemRow(idx)} disabled={reqItems.length === 1}>
                  X
                </Button>
              </div>
            ))}
          </div>

          {submitError ? <ErrorState error={submitError} /> : null}

          <div className="flex justify-end gap-3 pt-4 border-t border-slate-100">
            <Button variant="secondary" onClick={() => setModalOpen(false)}>Cancel</Button>
            <Button type="submit">Submit Requisition</Button>
          </div>
        </form>
      </Modal>
    </div>
  );
}
