import React, { useState } from 'react';
import {
  useGetRequisitionsQuery,
  useGetStoreInventoryQuery,
  useCreateRequisitionMutation,
} from '../../services/inventoryApi';
import { InventorySubNav } from './InventorySubNav';

export function RequisitionsPage() {
  const [isOpen, setIsOpen] = useState(false);
  const [notes, setNotes] = useState('');
  const [items, setItems] = useState([{ itemId: '', quantity: 1 }]);

  const { data: requisitions, isLoading, error, refetch } = useGetRequisitionsQuery();
  const { data: storeInventory } = useGetStoreInventoryQuery();
  const [createRequisition, { isLoading: isCreating }] = useCreateRequisitionMutation();

  const handleAddItemRow = () => {
    setItems([...items, { itemId: '', quantity: 1 }]);
  };

  const handleRemoveItemRow = (index) => {
    const updated = [...items];
    updated.splice(index, 1);
    setItems(updated);
  };

  const handleItemChange = (index, field, value) => {
    const updated = [...items];
    updated[index][field] = value;
    setItems(updated);
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    const payloadItems = items
      .filter((i) => i.itemId)
      .map((i) => ({
        itemId: Number(i.itemId),
        quantity: Number(i.quantity),
      }));

    if (payloadItems.length === 0) return;

    try {
      await createRequisition({
        notes,
        items: payloadItems,
      }).unwrap();
      setIsOpen(false);
      setNotes('');
      setItems([{ itemId: '', quantity: 1 }]);
      refetch();
    } catch (err) {
      console.error('Failed to create store requisition:', err);
    }
  };

  return (
    <div className="p-6 space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-slate-900 dark:text-white">Store Requisitions</h1>
          <p className="text-sm text-slate-500 dark:text-slate-400">
            Replenishment requests from Restaurant Store room to Main Warehouse.
          </p>
        </div>
        <button
          onClick={() => setIsOpen(true)}
          className="rounded-xl bg-amber-500 px-4 py-2.5 text-sm font-semibold text-white shadow-lg shadow-amber-500/20 hover:bg-amber-600 transition"
        >
          ➕ Request Store Requisition
        </button>
      </div>

      <InventorySubNav />

      {/* Warning/Info alert */}
      <div className="rounded-2xl bg-blue-500/10 border border-blue-500/20 p-4 text-blue-600 dark:text-blue-400 text-xs">
        ℹ️ **Warehouse Sync:** Requisitions are pushed securely to the Warehouse ERP system. Fulfillment and delivery issues are managed in the main ERP.
      </div>

      {isLoading ? (
        <div className="flex h-48 items-center justify-center">
          <div className="h-8 w-8 animate-spin rounded-full border-4 border-amber-500 border-t-transparent"></div>
        </div>
      ) : error ? (
        <div className="rounded-2xl bg-red-500/10 p-4 text-red-500">Failed to load requisitions.</div>
      ) : (
        <div className="space-y-4">
          {requisitions.map((req) => (
            <div
              key={req.id}
              className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 p-5 shadow-sm space-y-3"
            >
              <div className="flex items-center justify-between">
                <div>
                  <div className="flex items-center gap-2">
                    <h3 className="font-bold text-slate-900 dark:text-white text-base">Requisition: {req.requisitionNumber}</h3>
                    {req.isAutoGenerated && (
                      <span className="bg-amber-500/15 text-amber-600 text-[10px] font-bold px-2 py-0.5 rounded-full uppercase">
                        Auto Suggested
                      </span>
                    )}
                  </div>
                  <p className="text-xs text-slate-500">{new Date(req.createdAt).toLocaleString()}</p>
                </div>
                <span
                  className={`inline-flex rounded-full px-2.5 py-0.5 text-xs font-semibold ${
                    req.status === 'FULFILLED'
                      ? 'bg-emerald-500/10 text-emerald-600'
                      : 'bg-amber-500/10 text-amber-600'
                  }`}
                >
                  {req.status}
                </span>
              </div>

              {req.notes && <p className="text-xs italic text-slate-500 bg-slate-50 dark:bg-slate-800/40 p-2 rounded-xl">"{req.notes}"</p>}

              <div className="border-t border-slate-100 dark:border-slate-800 pt-2 text-xs">
                <table className="w-full text-left">
                  <thead>
                    <tr className="text-slate-400 font-semibold uppercase">
                      <th className="py-1">Ingredient Item</th>
                      <th className="py-1 text-right">Requested Qty</th>
                      <th className="py-1 text-right">Unit</th>
                    </tr>
                  </thead>
                  <tbody>
                    {req.items.map((ri) => (
                      <tr key={ri.id} className="border-b border-slate-50 dark:border-slate-800/20 last:border-b-0">
                        <td className="py-2 text-slate-900 dark:text-white font-medium">{ri.item.name}</td>
                        <td className="py-2 text-right font-bold">{ri.quantity}</td>
                        <td className="py-2 text-right text-slate-500">{ri.item.unit}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Create Requisition Request Modal */}
      {isOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 backdrop-blur-sm p-4 overflow-y-auto">
          <div className="w-full max-w-2xl rounded-3xl bg-white dark:bg-slate-900 p-6 shadow-2xl space-y-4 my-8">
            <div className="flex items-center justify-between border-b border-slate-200 dark:border-slate-800 pb-3">
              <h3 className="text-lg font-bold text-slate-900 dark:text-white">Request Store to Warehouse Requisition</h3>
              <button
                onClick={() => setIsOpen(false)}
                className="rounded-full bg-slate-100 dark:bg-slate-800 p-1.5 text-slate-400 hover:text-slate-900"
              >
                ✕
              </button>
            </div>

            <form onSubmit={handleSubmit} className="space-y-4">
              <div className="flex flex-col gap-1">
                <label className="text-xs font-semibold text-slate-500">Requisition Notes</label>
                <input
                  type="text"
                  value={notes}
                  onChange={(e) => setNotes(e.target.value)}
                  placeholder="e.g. Weekly stock restock request"
                  className="rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 px-3 py-2 text-sm"
                />
              </div>

              <div className="space-y-2 max-h-60 overflow-y-auto">
                <p className="text-xs font-bold text-slate-400 uppercase">Requested Items List</p>
                {items.map((row, idx) => {
                  const currentStoreItem = storeInventory?.find((s) => s.itemId === Number(row.itemId));
                  return (
                    <div key={idx} className="flex gap-3 items-center">
                      <select
                        required
                        value={row.itemId}
                        onChange={(e) => handleItemChange(idx, 'itemId', e.target.value)}
                        className="flex-1 rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 px-3 py-2 text-sm"
                      >
                        <option value="">Select Ingredient</option>
                        {storeInventory?.map((item) => (
                          <option key={item.id} value={item.itemId}>
                            {item.name}
                          </option>
                        ))}
                      </select>

                      <div className="w-28 flex items-center gap-1.5">
                        <input
                          type="number"
                          required
                          min="0.01"
                          step="0.01"
                          value={row.quantity}
                          onChange={(e) => handleItemChange(idx, 'quantity', e.target.value)}
                          className="w-full rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 px-3 py-2 text-sm"
                        />
                        <span className="text-xs text-slate-500 font-semibold">{currentStoreItem?.unit || ''}</span>
                      </div>

                      {items.length > 1 && (
                        <button
                          type="button"
                          onClick={() => handleRemoveItemRow(idx)}
                          className="text-rose-500 text-sm hover:underline font-bold px-2"
                        >
                          ✕
                        </button>
                      )}
                    </div>
                  );
                })}
              </div>

              <button
                type="button"
                onClick={handleAddItemRow}
                className="text-xs font-bold text-amber-500 hover:text-amber-600"
              >
                + Add Item
              </button>

              <div className="flex items-center justify-end gap-3 pt-4 border-t border-slate-200 dark:border-slate-800">
                <button
                  type="button"
                  onClick={() => setIsOpen(false)}
                  className="rounded-xl border border-slate-200 dark:border-slate-700 px-4 py-2.5 text-sm font-semibold text-slate-600 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-800"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={isCreating}
                  className="rounded-xl bg-amber-500 px-5 py-2.5 text-sm font-semibold text-white shadow-lg shadow-amber-500/20 hover:bg-amber-600 disabled:opacity-50"
                >
                  {isCreating ? 'Submitting...' : 'Submit Requisition'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
